.

diff --git a/0x0B-ssh/1-create_ssh_key_pair b/0x0B-ssh/1-create_ssh_key_pair
--- a/0x0B-ssh/1-create_ssh_key_pair
+++ b/0x0B-ssh/1-create_ssh_key_pair
@@ -1,4 +1,20 @@
 #!/usr/bin/env bash
-# Bash script that creates an RSA key pair
-#ssh-keygen -b 4096 -P betty -f school
-ssh-keygen -t rsa -b 4096 -P betty -f school
+# This script creates an RSA key pair named school with a passphrase betty.
+
+# Check if the key pair already exists
+if [ -e "school" ] || [ -e "school.pub" ]; then
+    echo "RSA key pair 'school' already exists."
+    exit 1
+fi
+
+# Generate the RSA key pair
+ssh-keygen -t rsa -b 4096 -N "betty" -f school
+
+# Check if the key pair was successfully created
+if [ $? -eq 0 ]; then
+    echo "RSA key pair 'school' created successfully."
+else
+    echo "Error: Failed to create RSA key pair."
+    exit 1
+fi
+
